### ISSUE TITLE
提几个改进点

### ISSUE THREAD

**Issue by kiccer** [FullStackFlamingo/vscode-vue-component-importer#7]
* 支持路径别名，比如 `@/components/custom.vue`
* 已经引用过的组件，不重复 `import` 引用，不重复在 `components` 中注册

**Comment by kiccer** [comment]
* 添加代码自动按照项目 `eslint` 规则进行格式化

**Comment by kiccer** [comment]
![image](https://user-images.githubusercontent.com/23536402/100853600-eb3ee700-34c2-11eb-98cb-21c6be17dd9a.png)
目前使用插件后路径是这样的，。

**Comment by FullStackFlamingo** [comment]
Thanks for your question, and thanks for using this extension.

Looks like Vetur now does `Auto import component` since [0.30.0](https://github.com/vuejs/vetur/releases/tag/v0.30.0), so I'll be deprecating this project, and I'll create a PR on vetur for `@/` fix. Vetur should have better relative imports and formatting.
